const PDFDocument = require("pdfkit");

const exportScanReport = (scan, res) => {
  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
    bufferPages: true,
  });

  // Pipe PDF directly to the response stream
  doc.pipe(res);

  // Ensures we never write past the bottom margin without a page break
  const checkPageBreak = (height = 60) => {
    if (doc.y + height > doc.page.height - 50) {
      doc.addPage();
    }
  };

  let pageNumber = 1;
  let drawingFooter = false; // guards against re-entrant addPage calls while footer text is written

  const addFooter = () => {
    if (drawingFooter) return;
    drawingFooter = true;

    const originalY = doc.y;
    const originalX = doc.x;

    doc
      .fontSize(9)
      .fillColor("gray")
      .text(
        "Generated by VulnScan",
        50,
        doc.page.height - 40,
        {
          align: "center",
          width: doc.page.width - 100,
          lineBreak: false,
        }
      );

    doc
      .fontSize(9)
      .fillColor("gray")
      .text(
        `Page ${pageNumber}`,
        50,
        doc.page.height - 28,
        {
          align: "center",
          width: doc.page.width - 100,
          lineBreak: false,
        }
      );

    // restore cursor so the footer never disturbs page flow
    doc.x = originalX;
    doc.y = originalY;

    drawingFooter = false;
  };

  // Draw footer on every new page as it's created
  doc.on("pageAdded", () => {
    pageNumber += 1;
    addFooter();
  });

  // Draw footer on the first page
  addFooter();

  // -------------Header-----------------
  doc
    .fontSize(28)
    .fillColor("#1E40AF")
    .text("VULNSCAN", {
      align: "center",
    });

  doc
    .moveDown(0.3)
    .fontSize(16)
    .fillColor("#374151")
    .text("Vulnerability Assessment Report", {
      align: "center",
    });

  doc
    .moveDown(0.3)
    .fontSize(11)
    .fillColor("gray")
    .text("Generated by VulnScan", {
      align: "center",
    });

  doc.moveDown(2);

  // ---------------Scan Summary---------------
  checkPageBreak(150);

  doc
    .fontSize(18)
    .fillColor("black")
    .text("Scan Summary");

  doc.moveDown();

  const summary = [
    ["Scan ID", scan._id],
    ["Target", scan.target],
    ["Target Type", scan.targetType],
    ["Status", scan.status],
    ["Risk Score", null], // rendered separately below with color
    [
      "Scan Date",
      new Date(scan.createdAt).toLocaleString(),
    ],
    ["Report Generated", new Date().toLocaleString()],
  ];

  summary.forEach(([label, value]) => {
    checkPageBreak(20);

    doc
      .font("Helvetica-Bold")
      .fillColor("black")
      .text(`${label}: `, {
        continued: true,
      });

    if (label === "Risk Score") {
      let scoreColor = "#16A34A";

      if (scan.riskScore >= 80) scoreColor = "#DC2626";
      else if (scan.riskScore >= 50) scoreColor = "#EA580C";
      else if (scan.riskScore >= 21) scoreColor = "#D97706";

      doc
        .font("Helvetica")
        .fillColor(scoreColor)
        .text(`${scan.riskScore}/100`);

      doc.fillColor("black");
    } else {
      doc
        .font("Helvetica")
        .text(value || "N/A");
    }
  });

  doc.moveDown(0.5);

  doc
    .font("Helvetica-Bold")
    .fillColor("black")
    .text("Report Version: ", { continued: true })
    .font("Helvetica")
    .text("1.0");

  doc
    .font("Helvetica-Bold")
    .text("Scanner: ", { continued: true })
    .font("Helvetica")
    .text("VulnScan");

  doc
    .font("Helvetica-Bold")
    .text("Generated By: ", { continued: true })
    .font("Helvetica")
    .text("VulnScan Backend");

  doc.moveDown(2);

  // ------------------------------
  // Executive Summary
  // ------------------------------

  const findingsCount = scan.findings?.length || 0;
  const portsCount = scan.ports?.length || 0;

  let overallRisk = "Low";

  if (scan.riskScore >= 80) overallRisk = "Critical";
  else if (scan.riskScore >= 50) overallRisk = "High";
  else if (scan.riskScore >= 21) overallRisk = "Medium";

  checkPageBreak(180);

  doc
    .fontSize(18)
    .fillColor("#111827")
    .text("Executive Summary");

  doc.moveDown(0.8);

  doc
    .fontSize(11)
    .fillColor("black")
    .text(
      `This vulnerability assessment evaluates the security posture of the target `
      + `"${scan.target}" by performing network port discovery, SSL/TLS certificate `
      + `validation, HTTP security header analysis, and basic vulnerability checks. `
      + `The findings presented in this report should be reviewed and remediated `
      + `according to their severity to reduce the overall attack surface.`
    );

  doc.moveDown();

  checkPageBreak(100);

  doc.font("Helvetica-Bold").fillColor("black").text("Overall Risk Level: ", { continued: true });

  switch (overallRisk) {
    case "Critical":
      doc.fillColor("#DC2626");
      break;

    case "High":
      doc.fillColor("#EA580C");
      break;

    case "Medium":
      doc.fillColor("#D97706");
      break;

    default:
      doc.fillColor("#16A34A");
  }

  doc.font("Helvetica").text(overallRisk);

  doc.fillColor("black");

  doc.moveDown();

  doc.font("Helvetica-Bold").text("Risk Score: ", { continued: true });
  {
    let scoreColor = "#16A34A";
    if (scan.riskScore >= 80) scoreColor = "#DC2626";
    else if (scan.riskScore >= 50) scoreColor = "#EA580C";
    else if (scan.riskScore >= 21) scoreColor = "#D97706";

    doc.font("Helvetica").fillColor(scoreColor).text(`${scan.riskScore}/100`);
    doc.fillColor("black");
  }

  doc.font("Helvetica").text(`Findings Detected: ${findingsCount}`);
  doc.text(`Open Ports: ${portsCount}`);
  doc.text(`Scan Status: ${scan.status}`);

  doc.moveDown(2);

  // ------------------------------
  // Port Analysis
  // ------------------------------

  checkPageBreak(120);

  doc
    .fontSize(18)
    .fillColor("#111827")
    .text("Port Analysis");

  doc.moveDown();

  const col1 = 60;
  const col2 = 180;
  const col3 = 320;

  const drawPortTableHeader = () => {
    const tableTop = doc.y;

    doc
      .font("Helvetica-Bold")
      .fontSize(11)
      .fillColor("black");

    doc.text("Port", col1, tableTop);
    doc.text("State", col2, tableTop);
    doc.text("Service", col3, tableTop);

    doc.moveDown(0.4);

    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor("#D1D5DB")
      .stroke();

    doc.moveDown(0.5);

    doc.font("Helvetica");
  };

  drawPortTableHeader();

  if (!scan.ports || scan.ports.length === 0) {
    doc.fillColor("black").text("No ports were detected.");
  }
  else {
    scan.ports.forEach((port) => {
      // If a row won't fit, start a new page and redraw the table header
      if (doc.y + 25 > doc.page.height - 50) {
        doc.addPage();
        drawPortTableHeader();
      }

      const y = doc.y;

      doc.fillColor("black");
      doc.text(port.port, col1, y);

      if (port.state === "open") {
        doc.fillColor("#16A34A");
      }
      else if (port.state === "filtered") {
        doc.fillColor("#D97706");
      }
      else {
        doc.fillColor("#DC2626");
      }

      doc.text(port.state, col2, y);

      doc.fillColor("black");
      doc.text(port.service || "Unknown", col3, y);

      doc.moveDown();
    });
  }

  doc.moveDown(2);

  // ------------------------------
  // SSL Certificate
  // ------------------------------

  checkPageBreak(150);

  doc
    .fontSize(18)
    .fillColor("#111827")
    .text("SSL/TLS Certificate");

  doc.moveDown();

  if (!scan.ssl) {

    doc
      .fontSize(11)
      .fillColor("#DC2626")
      .text("No SSL/TLS certificate information available.");

  } else {

    const ssl = scan.ssl;

    // Status
    checkPageBreak(20);

    doc
      .font("Helvetica-Bold")
      .fillColor("black")
      .text("Certificate Status: ", {
        continued: true,
      });

    if (ssl.valid) {
      doc.fillColor("#16A34A").text("VALID");
    } else {
      doc.fillColor("#DC2626").text("INVALID");
    }

    doc.moveDown();

    const rows = [
      ["Issuer", ssl.issuer],
      ["Subject", ssl.subject],
      [
        "Valid From",
        ssl.validFrom
          ? new Date(ssl.validFrom).toLocaleDateString()
          : "N/A",
      ],
      [
        "Valid Until",
        ssl.validTo
          ? new Date(ssl.validTo).toLocaleDateString()
          : "N/A",
      ],
      [
        "Days Remaining",
        ssl.expiresInDays != null
          ? `${ssl.expiresInDays} days`
          : "N/A",
      ],
    ];

    rows.forEach(([label, value]) => {
      // long issuer/subject strings can wrap onto multiple lines, so
      // reserve a bit more room before writing each row
      checkPageBreak(30);

      doc
        .font("Helvetica-Bold")
        .fillColor("black")
        .text(`${label}: `, {
          continued: true,
        });

      if (label === "Days Remaining" && ssl.expiresInDays != null) {
        let color = "#16A34A";

        if (ssl.expiresInDays < 15)
          color = "#DC2626";
        else if (ssl.expiresInDays < 30)
          color = "#F59E0B";

        doc
          .font("Helvetica")
          .fillColor(color)
          .text(value);
      }

      else {
        doc
          .font("Helvetica")
          .fillColor("#374151")
          .text(value || "N/A", {
            width: 470,
          });
      }
    });

  }

  doc.moveDown(2);

  // ------------------------------
  // Security Findings
  // ------------------------------

  checkPageBreak(120);

  doc
    .fontSize(18)
    .fillColor("#111827")
    .text("Security Findings");

  doc.moveDown();

  if (!scan.findings || scan.findings.length === 0) {

    doc
      .fontSize(11)
      .fillColor("#16A34A")
      .text("No vulnerabilities were detected during this scan.");

  } else {

    scan.findings.forEach((finding, index) => {

      // Keep boxes from splitting across pages
      checkPageBreak(115);

      //--------------------------------
      // Border Box
      //--------------------------------

      const startY = doc.y;

      doc
        .roundedRect(50, startY, 500, 115, 6)
        .strokeColor("#D1D5DB")
        .stroke();

      //--------------------------------
      // Finding Title
      //--------------------------------

      doc
        .fillColor("#111827")
        .font("Helvetica-Bold")
        .fontSize(12)
        .text(
          `${index + 1}. ${finding.title}`,
          60,
          startY + 12
        );

      //--------------------------------
      // Severity Badge
      //--------------------------------

      let badgeColor = "#6B7280";

      switch (finding.severity) {
        case "Critical":
          badgeColor = "#DC2626";
          break;

        case "High":
          badgeColor = "#EA580C";
          break;

        case "Medium":
          badgeColor = "#D97706";
          break;

        case "Low":
          badgeColor = "#16A34A";
          break;

        default:
          badgeColor = "#6B7280";
      }

      // Draw rounded badge
      doc
        .roundedRect(455, startY + 8, 75, 22, 10)
        .fill(badgeColor);

      // Badge text
      doc
        .fillColor("white")
        .font("Helvetica-Bold")
        .fontSize(10)
        .text(
          finding.severity.toUpperCase(),
          455,
          startY + 14,
          {
            width: 75,
            align: "center",
          }
        );

      //--------------------------------
      // Category
      //--------------------------------

      doc
        .fillColor("#2563EB")
        .fontSize(10)
        .text(
          `Category: ${finding.category}`,
          60,
          startY + 32
        );

      //--------------------------------
      // Description
      //--------------------------------

      doc
        .fillColor("black")
        .font("Helvetica")
        .fontSize(10)
        .text(
          finding.description,
          60,
          startY + 50,
          {
            width: 470,
          }
        );

      //--------------------------------
      // Recommendation
      //--------------------------------

      doc
        .font("Helvetica-Bold")
        .text(
          "Recommendation:",
          60,
          startY + 82,
          {
            continued: true,
          }
        );

      doc
        .font("Helvetica")
        .text(` ${finding.recommendation}`);

      doc.y = startY + 115;
      doc.moveDown(0.8);

    });

  }

  doc.moveDown();

  // ------------------------------
  // Overall Recommendations
  // ------------------------------

  doc.addPage();

  doc
    .fontSize(20)
    .fillColor("#111827")
    .text("Overall Recommendations");

  doc.moveDown();

  const recommendations = [];

  // Findings recommendations
  if (scan.findings?.length) {
    scan.findings.forEach((finding) => {
      if (
        finding.recommendation &&
        !recommendations.includes(finding.recommendation)
      ) {
        recommendations.push(finding.recommendation);
      }
    });
  }

  // Port recommendations
  const openPorts = scan.ports?.filter((p) => p.state === "open") || [];

  if (openPorts.length > 5) {
    recommendations.push(
      "Review all exposed ports and close any unnecessary services."
    );
  }

  // SSL recommendation
  if (scan.ssl && scan.ssl.expiresInDays < 30) {
    recommendations.push(
      "Renew the SSL/TLS certificate before expiration."
    );
  }

  if (!scan.ssl) {
    recommendations.push(
      "Enable HTTPS and deploy a valid SSL/TLS certificate."
    );
  }

  // Default recommendation
  if (recommendations.length === 0) {
    recommendations.push(
      "No major security issues were detected. Continue performing periodic vulnerability assessments and keep all services up to date."
    );
  }

  recommendations.forEach((recommendation) => {

    checkPageBreak(40);

    doc
      .circle(58, doc.y + 7, 2)
      .fill("#2563EB");

    doc
      .fillColor("black")
      .font("Helvetica")
      .fontSize(11)
      .text(
        recommendation,
        70,
        doc.y - 5,
        {
          width: 460,
        }
      );

    doc.moveDown();

  });

  doc.moveDown(2);

  checkPageBreak(120);

  doc
    .fontSize(18)
    .fillColor("#111827")
    .text("Final Assessment");

  doc.moveDown();

  let assessment = "";

  if (scan.riskScore >= 80) {
    assessment = "The scanned target presents a critical security posture and requires immediate remediation before being considered secure.";
  } 
  
  else if (scan.riskScore >= 50) {
    assessment = "The scanned target contains several high-risk issues that should be addressed as soon as possible.";
  } 
  
  else if (scan.riskScore >= 21) {
    assessment = "The scanned target contains moderate security issues. Recommended improvements should be implemented.";
  } 

  else {
    assessment = "The scanned target demonstrates a strong security posture with only minor observations recorded.";
  }

  doc
    .fontSize(11)
    .fillColor("#374151")
    .text(assessment, {
      align: "justify",
    });

  doc.moveDown(3);

  doc
    .fontSize(11)
    .fillColor("gray")
    .text("End of Report", {
      align: "center",
    });

  doc
    .fontSize(9)
    .fillColor("gray")
    .text("Generated by VulnScan", {
      align: "center",
    });

  doc.end();
}

module.exports = exportScanReport;